### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by PeterReid**
This includes work by engstad for cargo compatibility and rustc updates and then some updates by me for rustc updates on top of that. There isn't any new functionality.

### CODE REVIEW

**Comment by PeterReid** [comment]
No response on the licensing from engstad, so I redid my build fixes on top of your latest. This now builds with the latest rustc, but isn't cargo-fied. This is all squashed into one commit for merging now.

**Comment by klutzy** [comment]
Thanks again!

**Comment by engstad** [comment]
Sorry, shoot -- I didn't notice this thread. No probs using my stuff!

**Comment by engstad** [comment]
@PeterReid Fantastic work on the TLS stuff. I had a stab at it, but couldn't quite figure it out.

**Comment by PeterReid** [comment]
Thanks!

**Pull request merged**
